### ISSUE TITLE
webpack loader svg error

### ISSUE THREAD

**Issue by qiming520** [Rich-Harris/svg-parser#21]
Module build failed (from ./node_modules/@svgr/webpack/lib/index.js):
Error: Expected > (6:51). If this is valid SVG, it's probably a bug in svg-parser. Please raise an issue at https://github.com/Rich-Harris/svg-parser/issues – thanks!
`"content": "<symbol class=\"icon\" viewBox=\"0 0 1466 1024\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" id=\"icon-choose\"><defs><style type=\"text/css\"></style></defs><path d=\"M535.770344 1017.621782c-51.025747 0-102.051494-19.134655-140.320804-63.782184L19.134655 539.255403C-6.378218 513.742529 0 475.473219 25.512874 449.960345s63.782184-19.134655 89.295057 6.378219l376.314885 414.584195c25.512874 25.512874 63.782184 25.512874 89.295057 6.378218l6.378218-6.378218L1326.669424 22.619714c25.512874-25.512874 63.782184-31.891092 89.295057-6.378219 25.512874 25.512874 31.891092 63.782184 6.378219 89.295058L676.091149 953.839598l-12.756437 12.756437c-38.26931 31.891092-82.916839 51.025747-127.564368 51.025747z\" p-id=\"5002\" /></symbol>"`
at error (/Users/mac/Desktop/project/tools/mhc-h5/node_modules/svg-parser/src/index.js:30:9)
    at tag (/Users/mac/Desktop/project/tools/mhc-h5/node_modules/svg-parser/src/index.js:99:4)
    at parse (/Users/mac/Desktop/project/tools/mhc-h5/node_modules/svg-parser/src/index.js:224:11)
    at jsxPlugin (/Users/mac/Desktop/project/tools/mhc-h5/node_modules/@svgr/plugin-jsx/lib/index.js:20:41)
    at run (/Users/mac/Desktop/project/tools/mhc-h5/node_modules/@svgr/webpack/node_modules/@svgr/core/lib/convert.js:18:16)
    at convert (/Users/mac/Desktop/project/tools/mhc-h5/node_modules/@svgr/webpack/node_modules/@svgr/core/lib/convert.js:26:10)

 @ ./src/Icon2/type.ts 5:0-162 20:10-16
 @ ./src/Icon2/index.tsx
 @ ./src/Icon2/demo/index.tsx
 @ ./src/.umi/dumi/demos/Icon2.ts
 @ ./src/.umi/dumi/demos/index.ts
 @ ./src/Button/index.md
 @ ./src/.umi/core/routes.ts
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts

**Comment by AoDev** [comment]
I have the same issue.

**Comment by saidulsaikat** [comment]
same issue

**Comment by Sana348** [comment]
Same here.

**Comment by Augly** [comment]
Same here.

**Comment by speaceA** [comment]
same

**Comment by TrySound** [comment]
Looks like svg-parser got wrong input
